language: go
env:
- GO111MODULE=on
go:
- 1.12.x
os:
- linux
install: true
script:
- go test -v ./...
- env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o pass-tools-Linux-x86_64 ./cmd/pass-tools
- env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o pass-tools-Darwin-x86_64 ./cmd/pass-tools
- env GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o pass-tools-Windows-x86_64.exe ./cmd/pass-tools
deploy:
  provider: releases
  api_key:
    secure: uNR/n0ShHYJSHDRTUKTtvZIn60I0UXGemcWKIwgrFLFMbsAUItRlSpw5Rb13aNiYbU+ZW9RWWylUsHh1TisKmAGYKljyTeYGvA2X3tvx1Alue2/9oCyaed9Uz5lzK9YswqPq3NdFmUqQRKoin0CbRQKqYEyvTk7vGG7hBiXxSVWQSqcaQg26F1AS06JNnU/qwmjoqUEQbX6jqutqEKwVXsd//uObNXPQcGnpEAZGmzJF0tVT4rFKuKq7BvLAWUYle64qp1OtMSYm2h0Hl9sX3KCNgLilYqNyZV2T0/tYO1q80I4Mxk0FldM7QP52H2XO3DJM+yLTYWXpS1KEausVs/tDYck4/oxZaZaphHTKV3/GPekr4na8eW4KD7iPDSboKWuQO5VHucmWSH1Q3h+NV6eaGEIz2z6ONZuv/Gjo+jDrfAuaQ2hgSRDGImF4w5aFcqPoW4FflU861DPObEdEEbvD0XEjFp0vIgiOMJ9HpS2V/tiKEOWat7GhlyCGTHWlDp6qQACEnlqb4Zd8NczJJoLR6agKwbKmyE56LLo/5gtuW3mnomevM3fH4tWD6uh1VPRXehB0HuDvdgd+/cITH6w8uI8lyuOz/sabkvZYWhT8dXeOOJcLsnk0mCNr8APkrQlmlg9oSq0uASw83j1Lf3Hx9wufRq+HYJaVCjTrUcM=
  file: 
    - pass-tools-Linux-x86_64
    - pass-tools-Darwin-x86_64
    - pass-tools-Windows-x86_64.exe
  skip_cleanup: true
  on:
    tags: true
